alias win_dhc="cd /c/dev/sources/restlet/dhc/"
alias win_gwt_clean="rm -rf /c/Users/$(whoami)/AppData/Local/Temp/gwt*"
alias mac_gwt_clean="rm -rf /$TMPDIR/gwt*"
alias gfr="git f; git rebase;"
alias wip="git add -A; git commit -m\"WIP\""
alias dhc_build="win_dhc; mvn clean install -f pom-maven-plugin.xml -DskipTests; mvn clean install -DskipTests;"